export const tournaments = [
  {
    id: 1,
    trackName: "Gulfstream Park",
    location: "Hallandale Beach, FL",
    status: "LIVE",
    currentRace: 4,
    totalRaces: 10,
    prizeInfo: "Top 10 Ranked",
    players: 2847,
    maxPlayers: 5000,
    startTime: "2:00 PM EST",
    entryFee: "FREE",
    nextRace: "2:45 PM",
  },
  {
    id: 2,
    trackName: "Churchill Downs",
    location: "Louisville, KY",
    status: "LIVE",
    currentRace: 7,
    totalRaces: 12,
    prizeInfo: "Top 20 Ranked",
    players: 4102,
    maxPlayers: 5000,
    startTime: "1:00 PM EST",
    entryFee: "FREE",
    nextRace: "3:15 PM",
  },
  {
    id: 3,
    trackName: "Santa Anita Park",
    location: "Arcadia, CA",
    status: "UPCOMING",
    currentRace: 0,
    totalRaces: 8,
    prizeInfo: "Top 10 Ranked",
    players: 1253,
    maxPlayers: 5000,
    startTime: "5:00 PM PST",
    entryFee: "FREE",
    nextRace: "5:00 PM",
  },
];

export const topPlayers = [
  {
    rank: 1,
    username: "ThunderHoof",
    avatar: "TH",
    avatarColor: "#f59e0b",
    totalPoints: 14820,
    winRate: "68%",
    streak: 7,
    streakType: "win",
    tournamentsPlayed: 142,
  },
  {
    rank: 2,
    username: "GallopKing",
    avatar: "GK",
    avatarColor: "#a855f7",
    totalPoints: 13455,
    winRate: "62%",
    streak: 4,
    streakType: "win",
    tournamentsPlayed: 128,
  },
  {
    rank: 3,
    username: "RailRunner",
    avatar: "RR",
    avatarColor: "#06b6d4",
    totalPoints: 12890,
    winRate: "59%",
    streak: 3,
    streakType: "win",
    tournamentsPlayed: 155,
  },
  {
    rank: 4,
    username: "OddsWhisperer",
    avatar: "OW",
    avatarColor: "#10b981",
    totalPoints: 11740,
    winRate: "55%",
    streak: 1,
    streakType: "loss",
    tournamentsPlayed: 167,
  },
  {
    rank: 5,
    username: "FurlongMaster",
    avatar: "FM",
    avatarColor: "#ec4899",
    totalPoints: 10320,
    winRate: "52%",
    streak: 2,
    streakType: "win",
    tournamentsPlayed: 134,
  },
];

export const stats = [
  { label: "Players", value: "12,450+", icon: "users" },
  { label: "Live Tracks", value: "3", icon: "radio" },
  { label: "Entry Fee", value: "$0", icon: "zap" },
  { label: "Races", value: "24/7", icon: "clock" },
];

export const strategies = [
  {
    name: "Full Point",
    description: "Go all-in. Place all 50 points on a single horse for maximum risk and reward.",
    points: "50pts on 1 horse",
    risk: "High Risk",
    multiplier: "1x Odds Multiplier",
  },
  {
    name: "Dual Point",
    description: "Split your points between two horses. Balance risk with a safety net.",
    points: "25 + 25 split",
    risk: "Medium Risk",
    multiplier: "0.8x Odds Multiplier",
  },
  {
    name: "Smart Pick",
    description: "Spread across three horses. Maximize your chances of earning points each race.",
    points: "30 / 15 / 5 split",
    risk: "Low Risk",
    multiplier: "0.6x Odds Multiplier",
  },
];

export const howItWorks = [
  {
    step: 1,
    title: "Choose Your Strategy",
    description: "Pick how to distribute your 50 points: Full Point (all-in), Dual Point (split two), or Smart Pick (spread three).",
    icon: "target",
  },
  {
    step: 2,
    title: "Pick Your Horses",
    description: "Browse upcoming race cards, analyze the odds, study form guides, and make your selections before the race begins.",
    icon: "trophy",
  },
  {
    step: 3,
    title: "Climb the Leaderboard",
    description: "Your points are multiplied by the horse's odds when they win. Accumulate points across races to climb the rankings.",
    icon: "trending-up",
  },
];
