export const tournaments = [
  {
    id: 1,
    trackName: "Gulfstream Park",
    location: "Hallandale Beach, FL",
    status: "LIVE",
    currentRace: 4,
    totalRaces: 10,
    prizeInfo: "Top 10 Ranked",
    players: 2847,
    maxPlayers: 5000,
    startTime: "2:00 PM EST",
    entryFee: "FREE",
    nextRace: "2:45 PM",
  },
  {
    id: 2,
    trackName: "Churchill Downs",
    location: "Louisville, KY",
    status: "LIVE",
    currentRace: 7,
    totalRaces: 12,
    prizeInfo: "Top 20 Ranked",
    players: 4102,
    maxPlayers: 5000,
    startTime: "1:00 PM EST",
    entryFee: "FREE",
    nextRace: "3:15 PM",
  },
  {
    id: 3,
    trackName: "Santa Anita Park",
    location: "Arcadia, CA",
    status: "UPCOMING",
    currentRace: 0,
    totalRaces: 8,
    prizeInfo: "Top 10 Ranked",
    players: 1253,
    maxPlayers: 5000,
    startTime: "5:00 PM PST",
    entryFee: "FREE",
    nextRace: "5:00 PM",
  },
];

export const topPlayers = [
  {
    rank: 1,
    username: "ThunderHoof",
    avatar: "TH",
    avatarColor: "#f59e0b",
    totalPoints: 14820,
    winRate: "68%",
    streak: 7,
    streakType: "win",
    tournamentsPlayed: 142,
  },
  {
    rank: 2,
    username: "GallopKing",
    avatar: "GK",
    avatarColor: "#a855f7",
    totalPoints: 13455,
    winRate: "62%",
    streak: 4,
    streakType: "win",
    tournamentsPlayed: 128,
  },
  {
    rank: 3,
    username: "RailRunner",
    avatar: "RR",
    avatarColor: "#06b6d4",
    totalPoints: 12890,
    winRate: "59%",
    streak: 3,
    streakType: "win",
    tournamentsPlayed: 155,
  },
  {
    rank: 4,
    username: "OddsWhisperer",
    avatar: "OW",
    avatarColor: "#10b981",
    totalPoints: 11740,
    winRate: "55%",
    streak: 1,
    streakType: "loss",
    tournamentsPlayed: 167,
  },
  {
    rank: 5,
    username: "FurlongMaster",
    avatar: "FM",
    avatarColor: "#ec4899",
    totalPoints: 10320,
    winRate: "52%",
    streak: 2,
    streakType: "win",
    tournamentsPlayed: 134,
  },
];

export const stats = [
  { label: "Jugadores", value: "12,450+", icon: "users" },
  { label: "Pistas en Vivo", value: "3", icon: "radio" },
  { label: "Entrada", value: "Gratis", icon: "zap" },
  { label: "Carreras", value: "24/7", icon: "clock" },
];

export const strategies = [
  {
    name: "Full Point",
    description: "Todo en un solo caballo para maximo premio. 50 puntos en un solo caballo, maximo riesgo y recompensa.",
    points: "50pts en 1 caballo",
    risk: "Alto Riesgo",
    multiplier: "1x Multiplicador de Cuotas",
  },
  {
    name: "Dual Point",
    description: "Divide entre dos caballos para juego equilibrado. Equilibra el riesgo con una red de seguridad.",
    points: "25 + 25 dividido",
    risk: "Riesgo Medio",
    multiplier: "0.8x Multiplicador de Cuotas",
  },
  {
    name: "Smart Pick",
    description: "Distribuye en tres para puntuacion consistente. Maximiza tus chances de ganar puntos en cada carrera.",
    points: "30 / 15 / 5 dividido",
    risk: "Bajo Riesgo",
    multiplier: "0.6x Multiplicador de Cuotas",
  },
];

export const howItWorks = [
  {
    step: 1,
    title: "Elige tu Estrategia",
    description: "Elige como distribuir tus 50 puntos: Full Point (todo en uno), Dual Point (divide en dos), o Smart Pick (distribuye en tres).",
    icon: "target",
  },
  {
    step: 2,
    title: "Elige tus Caballos",
    description: "Explora las carreras, analiza las cuotas, estudia los formularios y haz tus selecciones antes de que comience la carrera.",
    icon: "trophy",
  },
  {
    step: 3,
    title: "Sube en la Clasificacion",
    description: "Tus puntos se multiplican por las cuotas del caballo cuando gana. Acumula puntos en todas las carreras para subir en el ranking.",
    icon: "trending-up",
  },
];
